server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 100
    min-spare-threads: 10
  servlet:
    context-path: /clr
  port: 8080
spring:
  profiles:
    active: dev
  dubbo:
      application:
        name: collectreport-manage
      server: true
      registry:
        address: zookeeper://192.168.11.128:2181
      protocol:
        name: dubbo
        port: 20880
mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations: classpath*:/mapper/**/*.xml
